#!/bin/bash -x
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".

recipients=$(git config hooks.mailinglist)

# For /usr/lib/sendmail
PATH=$PATH:/usr/lib/
echo "INFO: $0 running .."
while read oldrev newrev refname; do
    if [ -z "$(git rev-list $newrev..$oldrev)" ]; then
	# Fast forward, print out a mail per commit
	for rev in $(git rev-list $oldrev..$newrev | tac); do
#	    describe=$(git describe $rev 2>/dev/null)
#	    if [ -z "$describe" ]; then
	    describe=$(git show -s --abbrev-commit --pretty=oneline $rev)
	    if [ -z "$describe" ]; then
		describe="$rev"
	    fi
	    short_refname=${refname##refs/heads/}
	    cat | sendmail -t -oi <<-EOF
From: $(git show -s --pretty=tformat:"%cn <%ce>" "$rev")
To: $recipients
Subject: [$short_refname] $describe
Content-Type: text/plain; charset=utf-8


$(git show "$rev")
EOF
	done
    else
	sh /usr/share/doc/git-core/contrib/hooks/post-receive-email $refname $newrev $oldrev | sendmail -t -oi
    fi
done

